sudo: require

language: cpp

os:
    - linux

compiler:
    - gcc
    - clang

dist: trusty

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libgtest-dev valgrind cmake clang
    - sudo wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
    - sudo tar xf release-1.8.0.tar.gz
    - cd googletest-release-1.8.0/googletest
    - sudo cmake -DBUILD_SHARED_LIBS=ON .
    - sudo make
    - sudo cp -a include/gtest /usr/include
    - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
    - cd "${TRAVIS_BUILD_DIR}"

script:
    - cmake CMakeLists.txt
    - make
    - ./RefactoringKata

branches:
  only:
    - refactoring
