sudo: require

language: cpp

os:
    - linux

compiler:
    - gcc
    - clang

dist: trusty

source:
    - chmod 755 travis/cmake_install.sh travis/gcc_install.sh travis/gtest_install.sh
    - bash ./travis/cmake_install.sh
    - bash ./travis/gcc_install.sh
    - bash ./travis/gtest_install.sh

script:
    - cmake CMakeLists.txt
    - make
    - ./RefactoringKata
