sudo: require

language: cpp

os:
    - linux

compiler:
    - gcc
    - clang

dist: trusty

source:
    - cmake_install.sh
    - gcc_install.sh
    - gtest_install.sh

script:
    - cmake CMakeLists.txt
    - make
    - ./RefactoringKata
