sudo: require

language: cpp

os:
    - linux

compiler:
    - gcc
    - clang

dist: trusty

install:
    - chmod 755 travis/install_dependencies.sh
    - ./travis/install_dependencies.sh

script:
    - cmake CMakeLists.txt
    - make
    - ./RefactoringKata
